### ISSUE TITLE
Convert element HTML markup examples to `erb` includes

### ISSUE THREAD

**Issue by teenwolfblitzer** [Kajabi/sage-archived#159]
## Description
Use includes to modularize element markup. This could be especially useful when displaying multiple-element variations, and in constructing objects built from elements.

### Elements with multiple examples

- [x] Button (#189)
- [x] Checkbox (#193)
- [x] Danger Button (#207)
- [x] Form Input (#204)
- [x] Form Textarea (#205)
- [x] Form Select (#242)
- [x] Label (#199)
- [x] Live Stream Wrapper (#210)
- [x] Loader (#206)
- [x] Radio (#196)
- [x] Switch (#197)
- [x] Table (#211)
- [x] Tooltip (#192)

### Objects with multiple examples

- [x] Banner
- [x] Card (#219)
- [x] Live Avatar
- [x] Live Option Menu
- [x] Live Profile Card
- [x] Live Stream Control
- [x] Live Stream Footer
- [x] Live Stream Header
- [x] Live Stream Video Grid
- [x] Live User Control
- [x] Tabs (#225)
- [x] Pagination (#243)

### Elements with only one example

- [x] Description (#228)
- [x] Link Button (#246)

### Objects with only one example

- [x] Assistant (#182)
- [x] Form Section (#229 )
- [x] Live Active Mic (#241)
- [x] Nav (#232)
- [x] Page Heading (#239)
- [x] Panel (#240)
- [x] Sidebar (#234)

**Comment by philschanely** [comment]
Live Avatar covered in #160

**Comment by philschanely** [comment]
Live stream control, live stream header, and live stream footer were initially built this way.

**Comment by philschanely** [comment]
Live Stream Video Grid fixed in #164

**Comment by philschanely** [comment]
Live Option Menu, Live Profile Card, and Live User Control fixed in #168

**Comment by pixelflips** [comment]
Converted tooltip and checkboxes. Checked off in list above.

**Comment by pixelflips** [comment]
@monkeypox8 - correct me if I am wrong, but I don't think we need the standalone `link_button` element anymore, right? The `button` element takes care of those now, right?

**Comment by teenwolfblitzer** [comment]
> @monkeypox8 - correct me if I am wrong, but I don't think we need the standalone `link_button` element anymore, right? The `button` element takes care of those now, right?

Yes, I believe that's correct, though you may want to double-check with design to be sure.

**Comment by pixelflips** [comment]
@Kajabi/ux-devs - finally finished up the last of the conversions. Going to move this into landed and close this issue. Thanks for everyone's help with reviewing and helping out!
