### ISSUE TITLE
Finish incomplete documentation for Elements and Objects

### ISSUE THREAD

**Issue by teenwolfblitzer** [Kajabi/sage-archived#273]
## Description
We still have some scattered pieces in documentation that are incomplete

- **Elements**
- [x] Checkbox (#298)
- [x] Description (#314)
- [x] Form Select (#313)
- [x] Radios (#299)
- [x] Label (#300)
- [x] ~Link button~ - should be removed (#315)

- **Objects**
- [x] Alert (#272)
- [x] Billboard (#302)
- [x] Form section (#312)
- [x] Input helper (#261)
- [x] Nav (#306)
- [x] Page heading (#311)
- [x] Pagination (#304)
- [x] Panel (#305)
- [x] Tabs (#303)

## Related

- n/a

**Comment by pixelflips** [comment]
@monkeypox8 it looks like the input helper already has documentation. Can you please confirm?

**Comment by teenwolfblitzer** [comment]
> @monkeypox8 it looks like the input helper already has documentation. Can you please confirm?

Good call, I think we're set on that one. I'll remove it from the list.

**Comment by pixelflips** [comment]
@monkeypox8 it looks like the live elements in the list above have already been removed from the code base. I am going to remove them from the list above.

With that said, I believe the alert is the last to be completed. Do you want me to leave this issues open and you can check off and close once the alert updates are merged? Or should we check it off and then close this issue? I'm ok either way, but thought I'd get your thoughts as well.

**Comment by teenwolfblitzer** [comment]
> @monkeypox8 it looks like the live elements in the list above have already been removed from the code base. I am going to remove them from the list above.
> 
> With that said, I believe the alert is the last to be completed. Do you want me to leave this issues open and you can check off and close once the alert updates are merged? Or should we check it off and then close this issue? I'm ok either way, but thought I'd get your thoughts as well.

I think we're good to check off alert and close this one; I don't think we'll need to wait on the other PR. Thanks!
