### ISSUE TITLE
[BUG] Pagination does not display "current" state styling

### ISSUE THREAD

**Issue by teenwolfblitzer** [Kajabi/sage-archived#278]
## Description
Sage pagination component does not display the current page state in superadmin. There appears to be a mismatch in the classname used in the markup (`.sage-pagination__page--current`) vs the naming implemented in the CSS (`.sage-pagination__link--current`).

## Steps to reproduce
Describe the steps to reproduce the behavior: 
1. Log into the superadmin
2. Navigate to "users", "sites" or any other view with multiple pages of content
3. Note that the current page is not styled to indicate its state
4. Select a different page, and verify that the current page indicator does not update

## Screenshots
|  actual   |  expected  |
|--------|--------|
|![page--current-class](https://user-images.githubusercontent.com/816579/84077216-d2c69780-a98b-11ea-924c-fa043919ec6c.png)|![link--current](https://user-images.githubusercontent.com/816579/84077156-bfb3c780-a98b-11ea-9e83-b0da721f0ff0.png)|
page 3 is the current page number |page 20 is the current page number |

**Comment by pixelflips** [comment]
@monkeypox8 this was fixed in #326 and released in v1.3.0, mind if I close it?

**Comment by pixelflips** [comment]
Closing this as it was fixed in #326
