### ISSUE TITLE
Replace icon font with SVGs

### ISSUE THREAD

**Issue by teenwolfblitzer** [Kajabi/sage-archived#38]
We're currently using an icon font "Sage" to display iconography. We should consider replacing this with SVGs for the following additional benefits (among others):
- sizing/positioning consistency
- multi-color and animation options (manipulating individual paths)
- increased accessibility (titles are parsed by screenreaders)

May also want to use an SVG sprite sheet, combining symbols to reduce resource requests.

**Comment by philschanely** [comment]
@monkeypox8 Should we switch this back to `future`?
